<?php

namespace App\Services\Surat;

use PhpOffice\PhpWord\IOFactory;
use PhpOffice\PhpWord\Settings;

class DocxConverterService
{
    /**
     * Convert a .docx file to HTML string.
     */
    public function convert(string $absolutePath): string
    {
        if (! file_exists($absolutePath)) {
            throw new \RuntimeException("File DOCX tidak ditemukan: {$absolutePath}");
        }

        Settings::setTempDir(sys_get_temp_dir());

        $phpWord    = IOFactory::load($absolutePath);
        $htmlWriter = IOFactory::createWriter($phpWord, 'HTML');

        ob_start();
        $htmlWriter->save('php://output');
        $rawHtml = ob_get_clean();

        return $this->cleanHtml((string) $rawHtml);
    }

    /**
     * Clean, reformat, standardise, and auto-detect placeholders in HTML generated by PhpWord.
     */
    public function cleanHtml(string $html): string
    {
        // ── 1. Extract <body> content only ───────────────────────────────────────
        if (preg_match('/<body[^>]*>(.*?)<\/body>/is', $html, $m)) {
            $html = $m[1];
        }

        // ── 2. Strip XML namespaces, style blocks & Word bookmarks ──────────────
        $html = preg_replace('/<style[^>]*>.*?<\/style>/is', '', $html) ?? $html;
        $html = preg_replace('/\s*xmlns[^=]*="[^"]*"/', '', $html) ?? $html;
        $html = preg_replace('/([A-Za-z\s]+)\d{5,}/', '$1', $html) ?? $html;
        $html = preg_replace('/\b\d{6,}\b/', '', $html) ?? $html;

        // ── 3. Official Kop Surat ───────────────────────────────────────────────
        $kopHtml = <<<'HTML'
<table style="width: 100%; border-bottom: 3px double #000; margin-bottom: 14px; padding-bottom: 8px; border-collapse: collapse;">
  <tr>
    <td style="width: 85px; vertical-align: middle; text-align: center; padding-right: 10px;">
      <img src="/images/logo-malang.png" alt="Logo Kabupaten Malang" style="width: 75px; height: 75px; object-fit: contain;" />
    </td>
    <td style="vertical-align: middle; text-align: center; line-height: 1.25;">
      <p style="font-size: 11pt; font-weight: normal; margin: 0; text-transform: uppercase;">PEMERINTAH KABUPATEN MALANG</p>
      <p style="font-size: 11pt; font-weight: normal; margin: 0; text-transform: uppercase;">KECAMATAN TUMPANG</p>
      <p style="font-size: 15pt; font-weight: bold; margin: 1px 0; text-transform: uppercase;">DESA TULUSBESAR</p>
      <p style="font-size: 8.5pt; margin: 0;">Jalan Raya Tulusbesar No. 012 RT.04 RW.01, Kabupaten Malang, Jawa Timur</p>
      <p style="font-size: 8.5pt; margin: 0;">Telpon 0813-3311-4564 Laman : malangtulusbesar.desa.kemendesa.go.id</p>
      <p style="font-size: 8.5pt; margin: 0; text-decoration: underline;">Pos-el: email:pemdes.tulusbesar2018@gmail.com, Kode Pos : 65156</p>
    </td>
  </tr>
</table>
HTML;

        // ── 4. Detect Title of the Letter ───────────────────────────────────────
        $titleMatches = [];
        preg_match('/(SURAT\s+(?:KETERANGAN|PERNYATAAN|PENGANTAR|BORO)[^<\n]*)/i', $html, $titleMatches);
        $titleText = ! empty($titleMatches[1]) ? trim(strip_tags($titleMatches[1])) : 'SURAT KETERANGAN';

        // ── 5. Flatten fragmented tables into normalized lines ──────────────────
        $html = preg_replace_callback('/<table[^>]*>(.*?)<\/table>/is', function ($tbl) {
            $content = $tbl[1];
            if (preg_match('/PEMERINTAH|KABUPATEN\s+MALANG/i', $content)) {
                return '';
            }
            $rowsHtml = '';
            if (preg_match_all('/<tr[^>]*>(.*?)<\/tr>/is', $content, $trMatches)) {
                foreach ($trMatches[1] as $tr) {
                    if (preg_match_all('/<(?:td|th)[^>]*>(.*?)<\/(?:td|th)>/is', $tr, $tdMatches)) {
                        $cells = array_map(fn ($c) => trim(strip_tags($c)), $tdMatches[1]);
                        if (count($cells) >= 2) {
                            $label = $cells[0];
                            $val   = '';
                            for ($i = count($cells) - 1; $i >= 1; $i--) {
                                if ($cells[$i] !== '' && $cells[$i] !== ':') {
                                    $val = $cells[$i];
                                    break;
                                }
                            }
                            $rowsHtml .= "<p>{$label} : {$val}</p>\n";
                        }
                    }
                }
            }
            return $rowsHtml;
        }, $html) ?? $html;

        // ── 6. Parse Line by Line with Context Tracking ─────────────────────────
        $lines                  = preg_split('/(?:<\/p>|<br\s*\/?>|\n|<\/tr>)/is', $html) ?: [];
        $currentContext         = 'warga';
        $parsedElements         = [];
        $hasPassedTitle         = false;
        $isFinished             = false;

        foreach ($lines as $line) {
            $rawText = trim(strip_tags($line));
            $rawText = html_entity_decode($rawText, ENT_QUOTES | ENT_HTML5, 'UTF-8');
            $rawText = preg_replace('/[\t\x{00a0}]+/u', ' ', $rawText) ?? $rawText;
            $rawText = trim($rawText);

            if (empty($rawText)) {
                continue;
            }

            if ($isFinished) {
                continue;
            }

            // Check if letter title reached
            if (preg_match('/SURAT\s+(?:KETERANGAN|PERNYATAAN|PENGANTAR|BORO)/i', $rawText)) {
                $hasPassedTitle = true;
                continue;
            }

            // Skip everything in header before title
            if (! $hasPassedTitle) {
                continue;
            }

            // Skip Nomor line (we generate standard)
            if (preg_match('/^Nomor\s*:/i', $rawText)) {
                continue;
            }

            // Section Context Headings:
            if (preg_match('/telah\s+meninggal\s+dunia/i', $rawText)) {
                $currentContext = 'kematian';
                $parsedElements[] = ['type' => 'heading', 'text' => 'Telah meninggal dunia pada :'];
                continue;
            }
            if (preg_match('/^pelapor\s*:?$/i', $rawText)) {
                $currentContext = 'pelapor';
                $parsedElements[] = ['type' => 'heading', 'text' => 'Pelapor :'];
                continue;
            }
            if (preg_match('/telah\s+lahir\s+seorang\s+anak/i', $rawText)) {
                $currentContext = 'anak';
                $parsedElements[] = ['type' => 'heading', 'text' => 'Telah lahir seorang anak :'];
                continue;
            }
            if (preg_match('/dari\s+seorang\s+ibu/i', $rawText)) {
                $currentContext = 'ibu';
                $parsedElements[] = ['type' => 'heading', 'text' => 'Dari seorang ibu :'];
                continue;
            }
            if (preg_match('/dari\s+seorang\s+ayah/i', $rawText)) {
                $currentContext = 'ayah';
                $parsedElements[] = ['type' => 'heading', 'text' => 'Dari seorang ayah :'];
                continue;
            }

            // Closing sentence
            if (preg_match('/demikian\s+surat/i', $rawText)) {
                $parsedElements[] = ['type' => 'paragraph', 'text' => $rawText];
                $isFinished = true;
                continue;
            }

            // If signature date / pelapor encountered before closing sentence
            if (preg_match('/^Tulusbesar,\s*\d+/i', $rawText) || preg_match('/^(?:Kepala\s+Desa|Pelapor,)/i', $rawText)) {
                $isFinished = true;
                continue;
            }

            // Opening Narrative
            if (preg_match('/yang\s+bertanda\s+tangan/i', $rawText)) {
                $parsedElements[] = ['type' => 'paragraph', 'text' => $rawText];
                continue;
            }

            // Key-Value row: Label : Value
            if (preg_match('/^([^:]+)\s*:\s*(.*)$/u', $rawText, $kvMatch)) {
                $label = trim($kvMatch[1]);
                $val   = trim($kvMatch[2]);
                $norm  = strtolower($label);

                $tag      = self::mapLabelToTag($norm, $currentContext);
                $finalVal = (! empty($val) && preg_match('/\{\{[a-z_]+\}\}/', $val)) ? $val : $tag;

                $parsedElements[] = [
                    'type'  => 'field',
                    'label' => self::formatDisplayLabel($label),
                    'value' => $finalVal,
                ];
                continue;
            }

            // Fallback narrative paragraph
            $parsedElements[] = ['type' => 'paragraph', 'text' => $rawText];
        }

        // ── 7. Build Standardized HTML Output ────────────────────────────────────
        $out = $kopHtml . "\n";
        $out .= '<h4 style="text-align: center; font-size: 12pt; font-weight: bold; text-decoration: underline; margin: 10px 0 2px; text-transform: uppercase;">' . $titleText . '</h4>' . "\n";
        $out .= '<p style="text-align: center; margin: 0 0 12px; font-size: 10.5pt;">Nomor : {{nomor_surat}}</p>' . "\n";

        $inTable = false;

        foreach ($parsedElements as $el) {
            if ($el['type'] === 'field') {
                if (! $inTable) {
                    $out .= '<table style="width: 100%; border-collapse: collapse; margin-bottom: 6px;">' . "\n";
                    $inTable = true;
                }
                $out .= '  <tr>' . "\n"
                     . '    <td style="width: 160px; padding: 2px 0; vertical-align: top;">' . htmlspecialchars($el['label']) . '</td>' . "\n"
                     . '    <td style="width: 20px; padding: 2px 0; vertical-align: top; text-align: center;">:</td>' . "\n"
                     . '    <td style="padding: 2px 0; vertical-align: top;">' . $el['value'] . '</td>' . "\n"
                     . '  </tr>' . "\n";
            } else {
                if ($inTable) {
                    $out .= '</table>' . "\n";
                    $inTable = false;
                }
                if ($el['type'] === 'heading') {
                    $out .= '<p style="margin: 8px 0 3px; font-weight: bold;">' . htmlspecialchars($el['text']) . '</p>' . "\n";
                } elseif ($el['type'] === 'paragraph') {
                    $out .= '<p style="text-align: justify; margin: 6px 0; line-height: 1.4;">' . htmlspecialchars($el['text']) . '</p>' . "\n";
                }
            }
        }

        if ($inTable) {
            $out .= '</table>' . "\n";
        }

        // ── 8. Clean Signature Block ─────────────────────────────────────────────
        if ($currentContext === 'pelapor' || preg_match('/kematian|pernyataan/i', $titleText)) {
            $out .= <<<'HTML'
<table style="width: 100%; margin-top: 24px; border-collapse: collapse;">
  <tr>
    <td style="width: 50%; vertical-align: top; text-align: center;">
      <p style="margin: 0 0 55px;">Pelapor,</p>
      <p style="margin: 0; font-weight: bold; text-decoration: underline;">{{nama_pelapor}}</p>
    </td>
    <td style="width: 50%; vertical-align: top; text-align: center;">
      <p style="margin: 0;">Tulusbesar, {{tanggal_surat}}</p>
      <p style="margin: 0 0 55px; font-weight: bold; text-transform: uppercase;">Kepala Desa Tulusbesar,</p>
      <p style="margin: 0; font-weight: bold; text-decoration: underline; text-transform: uppercase;">{{nama_kepala_desa}}</p>
    </td>
  </tr>
</table>
HTML;
        } else {
            $out .= <<<'HTML'
<table style="width: 100%; margin-top: 24px; border-collapse: collapse;">
  <tr>
    <td style="width: 50%; vertical-align: top; text-align: center;"></td>
    <td style="width: 50%; vertical-align: top; text-align: center;">
      <p style="margin: 0;">Tulusbesar, {{tanggal_surat}}</p>
      <p style="margin: 0 0 55px; font-weight: bold; text-transform: uppercase;">Kepala Desa Tulusbesar,</p>
      <p style="margin: 0; font-weight: bold; text-decoration: underline; text-transform: uppercase;">{{nama_kepala_desa}}</p>
    </td>
  </tr>
</table>
HTML;
        }

        return trim($out);
    }

    /**
     * Map any Indonesian letter label into a standardized placeholder tag.
     */
    private static function mapLabelToTag(string $norm, string $context): string
    {
        if (preg_match('/^nama/i', $norm)) {
            if ($context === 'pelapor') {
                return '{{nama_pelapor}}';
            }
            if ($context === 'anak') {
                return '{{nama_anak}}';
            }
            if ($context === 'ibu') {
                return '{{nama_ibu}}';
            }
            if ($context === 'ayah') {
                return '{{nama_ayah}}';
            }
            return '{{nama}}';
        }
        if (preg_match('/^nik\b|no\.?\s*ktp/i', $norm)) {
            if ($context === 'pelapor') {
                return '{{nik_pelapor}}';
            }
            if ($context === 'anak') {
                return '{{nik_anak}}';
            }
            if ($context === 'ibu') {
                return '{{nik_ibu}}';
            }
            if ($context === 'ayah') {
                return '{{nik_ayah}}';
            }
            return '{{nik}}';
        }
        if (preg_match('/jenis\s+kelamin/i', $norm)) {
            if ($context === 'pelapor') {
                return '{{jenis_kelamin_pelapor}}';
            }
            if ($context === 'anak') {
                return '{{jenis_kelamin_anak}}';
            }
            return '{{jenis_kelamin}}';
        }
        if (preg_match('/alamat/i', $norm)) {
            if ($context === 'pelapor') {
                return '{{alamat_pelapor}}';
            }
            if ($context === 'ibu') {
                return '{{alamat_ibu}}';
            }
            if ($context === 'ayah') {
                return '{{alamat_ayah}}';
            }
            return '{{alamat}}';
        }
        if (preg_match('/pekerjaan/i', $norm)) {
            if ($context === 'ibu') {
                return '{{pekerjaan_ibu}}';
            }
            if ($context === 'ayah') {
                return '{{pekerjaan_ayah}}';
            }
            return '{{pekerjaan}}';
        }
        if (preg_match('/umur\b|usia\b/i', $norm)) {
            return '{{umur}}';
        }
        if (preg_match('/hubungan\s+keluarga/i', $norm)) {
            return '{{hubungan_keluarga}}';
        }
        if (preg_match('/sebab\s+kematian/i', $norm)) {
            return '{{sebab_kematian}}';
        }
        if (preg_match('/^jam\b|^pukul\b/i', $norm)) {
            return '{{jam_meninggal}}';
        }
        if (preg_match('/^di\b|tempat\s+meninggal/i', $norm)) {
            return '{{tempat_meninggal}}';
        }
        if (preg_match('/^hari\b/i', $norm)) {
            return ($context === 'kematian') ? '{{hari_meninggal}}' : '{{hari_lahir}}';
        }
        if (preg_match('/^tanggal\b|^tgl\b/i', $norm)) {
            return ($context === 'kematian') ? '{{tanggal_meninggal}}' : '{{tanggal_lahir}}';
        }
        if (preg_match('/tempat.*(?:tgl|tanggal).*lahir/i', $norm) || preg_match('/^ttl\b/i', $norm)) {
            return '{{tempat_tanggal_lahir}}';
        }
        if (preg_match('/tempat\s+lahir/i', $norm)) {
            return ($context === 'anak') ? '{{tempat_lahir_anak}}' : '{{tempat_lahir}}';
        }
        if (preg_match('/agama/i', $norm)) {
            return '{{agama}}';
        }
        if (preg_match('/status\s*(?:perkawinan|pernikahan)?/i', $norm)) {
            return '{{status_perkawinan}}';
        }
        if (preg_match('/sekolah/i', $norm)) {
            return '{{nama_sekolah}}';
        }
        if (preg_match('/kelas/i', $norm)) {
            return '{{kelas_anak}}';
        }
        if (preg_match('/keperluan/i', $norm)) {
            return '{{keperluan}}';
        }
        if (preg_match('/nama\s+usaha/i', $norm)) {
            return '{{nama_usaha}}';
        }
        if (preg_match('/jenis\s+usaha/i', $norm)) {
            return '{{jenis_usaha}}';
        }
        if (preg_match('/alamat\s+usaha/i', $norm)) {
            return '{{alamat_usaha}}';
        }
        if (preg_match('/penghasilan/i', $norm)) {
            return '{{penghasilan}}';
        }

        $cleanKey = preg_replace('/[^a-z0-9_]+/', '_', $norm);
        return '{{' . trim((string) $cleanKey, '_') . '}}';
    }

    /**
     * Format display label nicely.
     */
    private static function formatDisplayLabel(string $label): string
    {
        $trim = trim($label);
        if (strcasecmp($trim, 'nik') === 0) {
            return 'NIK';
        }
        if (strcasecmp($trim, 'ttl') === 0) {
            return 'Tempat, Tgl. Lahir';
        }
        if (strcasecmp($trim, 'di') === 0) {
            return 'Di';
        }
        return ucwords(strtolower($trim));
    }
}
